const CMS_MODULES = {
  MAIN: "Main",
  TEXTS: "Texts",
  MEDIA: "Media",
  LINKS: "Links",
  META_TAGS: "MetaTags",
  GENERAL_INFO: "GeneralInfo",
  USERS: "Users",
  IAM_ROLE: "IAMRole",
  ITEMS: "Items",
  ITEMS_MENU: "ItemsMenu",
  ITEM_INGREDIENTS: "ItemIngredients",
  INGREDIENTS_MENU: "IngredientsMenu",
  STUDENTS: "Students",
  TEACHERS: "Teachers",
  INSTRUCTORS: "Instructors",
  COURSES: "Courses",
  REGISTER: "Register",
  ATTENDANCE: "Attendance",
};
export default CMS_MODULES;
