const DYNAMIC_PAGE_COMPONENTS_ID = {
  EDITOR: "EDITOR",
  MEDIA: "MEDIA",
  MEDIA_CAROUSEL: "MEDIA_CAROUSEL",
  MEDIA_SLIDER: "MEDIA_SLIDER",
  RATING: "RATING",
};
export default DYNAMIC_PAGE_COMPONENTS_ID;
