const FORM_INPUTS_TYPES = {
  INPUT: "input",
  RADIO: "radio",
  AUTO_COMPLETE: "auto-complete",
  SELECT: "select",
  ANIMATED_INPUT: "animated-input",
  TEXT_AREA: "text-area",
  ANIMATED_TEXT_AREA: "animated-text-area",
  AUTO_GROW_TEXT_AREA: "auto-grow-text-area",
  ANIMATED_AUTO_GROW_TEXT_AREA: "animated-auto-grow-text-area",
  FILE_UPLOAD: "file-upload",
  CHECKBOXES: "checkboxes",
  CHECKBOX: "checkbox",
  BITWISE_CHECKBOX: "bitwise-checkboxes",
  MULTI_SELECT_AUTO_COMPLETE: "multi-select-auto-complete",
  MULTI_SELECT: "multi-select",
  TIME_PICKER: "time-picker",
  DATE_PICKER: "date-picker",
  BORDER_INPUT: "border-input",
  EDITOR: "editor",
  MEDIA: "media",
  MEDIA_MULTI_SELECT: "media-multi-select",
  LANGUAGE_SELECT: "language-select",
  RATING_INPUT: "rating-input",
};
export default FORM_INPUTS_TYPES;
