const POPUP_TYPES = {
  API_ERROR: "API_ERROR",
  BASIC: "BASIC",
  TEXTS: "TEXTS",
  MEDIA: "MEDIA",
  EDIT_GENERAL_INFO: "EDIT_GENERAL_INFO",
  GENERAL_INFO: "GENERAL_INFO",
  LINKS: "LINKS",
  META_TAGS: "META_TAGS",
  IAM_ROLE: "IAM_ROLE",
  CREATE_USER: "CREATE_USER",
  TRASH: "TRASH",
  UPDATE_USER: "UPDATE_USER",
  ITEMS: "ITEMS",
  ITEMS_MENU: "ITEMS_MENU",
  ITEM_INGREDIENTS: "ITEM_INGREDIENTS",
  PRODUCT: "PRODUCT",
  FILES: "FILES",
};

export default POPUP_TYPES;
