const TABLE_CELL_TYPES = {
  TEXT: "TEXT",
  TEXT_FROM_DATASET: "TEXT_FROM_DATASET",
  COLORED_CELL: "COLORED_CELL",
  CHECKBOX: "CHECKBOX",
  ACTION_BUTTONS: "ACTION_BUTTONS",
  INPUT: "INPUT",
  COUNT_ROWS: "COUNT_ROWS",
};

export default TABLE_CELL_TYPES;

export const TABLE_ACTION_TYPES = {
  TEXT: "TEXT",
  ICON: "ICON",
  ICON_TEXT: "ICON_TEXT",
};
